import localFont from "next/font/local";
import "./globals.css";
import Header from "./Header/page"
import Navbar from "./Navbar/page"
// const geistSans = localFont({
//   src: "",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Lawrence View Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
